-- Atualiza watched (Numero de filmes assistidos em USER_
-- PL EDSON
CREATE OR REPLACE PROCEDURE UPDATE_WATCHED_MOVIES_PROC (p_user_id IN NUMBER) AS
    v_watched_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_watched_count
    FROM WATCHES_
    WHERE ID_USER = p_user_id;

    UPDATE USER_
    SET WATCHED = v_watched_count
    WHERE ID = p_user_id;
END;

CREATE OR REPLACE TRIGGER UPDATE_ALL_WATCHED_MOVIES_AFTER_INSERT
AFTER INSERT ON WATCHES_
BEGIN
    FOR r IN (SELECT DISTINCT ID_USER FROM WATCHES_) LOOP
        UPDATE_WATCHED_MOVIES_PROC(r.ID_USER);
    END LOOP;
END;

-- PL MARCONDES
-- Atualiza N_ACTED
CREATE OR REPLACE TRIGGER UPDATE_N_ACTED_AFTER_INSERT
AFTER INSERT ON PLAYED_BY
FOR EACH ROW
BEGIN
  UPDATE CREW_MEMBER
  SET N_ACTED = N_ACTED + 1
  WHERE ID = :NEW.ID_CREW;
END;

-- Atualiza N_DIRECTED
CREATE OR REPLACE TRIGGER UPDATE_N_DIRECTED_AFTER_INSERT
AFTER INSERT ON DIRECTS
FOR EACH ROW
BEGIN
  UPDATE CREW_MEMBER
  SET N_DIRECTED = N_DIRECTED + 1
  WHERE ID = :NEW.ID_CREW;
END;
